#!/bin/sh
# chkconfig: 123456 90 10
# TTS Server for Speech Synthesis
#

options="--config-file /etc/SciPass/ryu.conf --use-syslog --nouse-stderr"

CMD="ryu-manager /usr/lib/python2.6/site-packages/SciPass/Ryu.py $options"
 
start() {
    $CMD 2>&1 &
    echo "SciPass Started"
}
 
stop() {
    pid=`ps -ef | grep 'ryu-manager /usr/lib/python2.6/site-packages/SciPass/Ryu.py' | grep -v "grep" | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "SciPass Stopped"
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/scipass {start|stop|restart}"
    exit 1
esac
exit 0